### ISSUE TITLE
Whats this?

### ISSUE THREAD

**Issue by lsolberg** [telligro/opal-node-red#10]
Can you shed some light on what this project is all about?
Currently, there are nodes that we are unable to install inside the main node-red repo (flows.nodered.org).

It's really confusing.. Can you either write a warning on each package, or make another repo (depending on how big this opal-framework is).

Just some info would be nice :)

**Comment by shivamadhavan** [comment]
@lsolberg The nodes maintained as part of the OPAL framework do not support installation in **node-red**. They are supported only by the **opal-node-red** fork. I understand that until a time when these nodes can be installed in node-red, they should not be indexed by the flows.nodered.org. We will be making the changes necessary to effect that.

OPAL is a framework that aims to define the next generation of process automation with Robotic Process Automation(RPA) as one of its building blocks. The [opal-node-red](https://github.com/telligro/opal-node-red), [opal-nodes](https://github.com/telligro/opal-nodes) and [opal-setup](https://github.com/telligro/opal-setup) are repositories associated with this framework. 

More details about the OPAL framework and applicable use cases will be made available in the coming weeks through the repo README and associated web sites.

Thanks for your interest.

Cheers,
Shiva
